services:
  ez-db:
    image: postgres:16
    container_name: ez-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ezuser
      POSTGRES_PASSWORD: ezpass
      POSTGRES_DB: ezapply_dev
    ports:
      - "5432:5432"
    volumes:
      - ez-db-data:/var/lib/postgresql/data
volumes:
  ez-db-data:
